type ReviewData = {
  bottleId: string;
  name: string;
  type: string;
  status: string;
  distillery: string;
  country: string;
  region: string;
  price: string;
  age: string;
  alcoholPercent: string;
  year: string;
  barrel: string;
  finishing: string;
  imageUrl: string;
  date: string;
  setting: string;
  glassware: string;
  restTime: string;
  nose: string;
  palate: string;
  finish: string;
  thoughts: string;
  fruity: number;
  nutty: number;
  spicy: number;
  herbal: number;
  tobacco: number;
  leather: number;
  oak: number;
  grain: number;
  vanilla: number;
  caramel: number;
  honey: number;
  chocolate: number;
  value: number;
  overallRating: number;
};

export type RedisFormData = { formId: string } & Partial<ReviewData>;
